const argumentsConfig = [
    {
        name: '--listen',
        type: 'text',
        defaultValue: '127.0.0.1',
        description: 'Specify the IP address to listen on (default: 127.0.0.1). If --listen is provided without an argument, it defaults to 0.0.0.0. (listens on all)',
        prefix: true,
    },
    {
        name: '--port',
        type: 'number',
        defaultValue: 8188,
        description: 'Set the listen port.',
        prefix: true,
    },
    {
        name: '--tls-keyfile',
        type: 'text',
        defaultValue: '',
        description: 'Path to TLS (SSL) key file. Enables TLS, makes app accessible at https://... requires --tls-certfile to function',
        prefix: true,
    },
    {
        name: '--tls-certfile',
        type: 'text',
        defaultValue: '',
        description: 'Path to TLS (SSL) certificate file. Enables TLS, makes app accessible at https://... requires --tls-keyfile to function',
        prefix: true,
    },
    {
        name: '--enable-cors-header',
        type: 'text',
        defaultValue: '*',
        description: "Enable CORS (Cross-Origin Resource Sharing) with optional origin or allow all with default '*'.",
        prefix: true,
    },
    {
        name: '--max-upload-size',
        type: 'number',
        defaultValue: 100,
        description: 'Set the maximum upload size in MB.',
        prefix: true,
    },
    {
        name: '--extra-model-paths-config',
        type: 'text',
        defaultValue: '',
        description: 'Load one or more extra_model_paths.yaml files.',
        prefix: true,
    },
    {
        name: '--output-directory',
        type: 'text',
        defaultValue: '',
        description: 'Set the ComfyUI output directory.',
        prefix: true,
    },
    {
        name: '--temp-directory',
        type: 'text',
        defaultValue: '',
        description: 'Set the ComfyUI temp directory (default is in the ComfyUI directory).',
        prefix: true,
    },
    {
        name: '--input-directory',
        type: 'text',
        defaultValue: '',
        description: 'Set the ComfyUI input directory.',
        prefix: true,
    },
    {
        name: '--auto-launch',
        type: 'checkbox',
        description: 'Automatically launch ComfyUI in the default browser.',
        prefix: false,
    },
    {
        name: '--disable-auto-launch',
        type: 'checkbox',
        description: 'Disable auto launching the browser.',
        prefix: false,
    },
    {
        name: '--cuda-device',
        type: 'number',
        defaultValue: 0,
        description: 'Set the id of the CUDA device this instance will use.',
        prefix: true,
    },
    {
        name: 'fpvae',
        type: 'select',
        options: [
            { value: '--fp16-vae', label: '--fp16-vae' },
            { value: '--fp32-vae', label: '--fp32-vae' },
            { value: '--bf16-vae', label: '--bf16-vae' },
        ],
        description: 'Floating Point precision options for VAE. Available values: --fp16-vae, --fp32-vae, --bf16-vae.',
    },
    {
        name: 'fpunet',
        type: 'select',
        options: [
            { value: '--bf16-unet', label: '--bf16-unet' },
            { value: '--fp16-unet', label: '--fp16-unet' },
            { value: '--fp8_e4m3fn-unet', label: '--fp8_e4m3fn-unet' },
            { value: '--fp8_e5m2-unet', label: '--fp8_e5m2-unet' },
        ],
        description: 'Floating Point precision options for UNET. Available values: --bf16-unet, --fp16-unet, --fp8_e4m3fn-unet, --fp8_e5m2-unet.',
    },
    {
        name: 'fpte',
        type: 'select',
        options: [
            { value: '--fp8_e4m3fn-text-enc', label: '--fp8_e4m3fn-text-enc' },
            { value: '--fp8_e5m2-text-enc', label: '--fp8_e5m2-text-enc' },
            { value: '--fp16-text-enc', label: '--fp16-text-enc' },
            { value: '--fp32-text-enc', label: '--fp32-text-enc' },
        ],
        description: 'Floating Point precision options for Text Encoder. Available values: --fp8_e4m3fn-text-enc, --fp8_e5m2-text-enc, --fp16-text-enc, --fp32-text-enc.',
    },
    {
        name: 'cache',
        type: 'select',
        options: [
            { value: '--cache-classic', label: '--cache-classic' },
            { value: '--cache-lru', label: '--cache-lru' },
        ],
        description: 'Cache configuration options. Available values: --cache-classic, --cache-lru.',
    },
    {
        name: 'attn',
        type: 'select',
        options: [
            { value: '--use-split-cross-attention', label: '--use-split-cross-attention' },
            { value: '--use-quad-cross-attention', label: '--use-quad-cross-attention' },
            { value: '--use-pytorch-cross-attention', label: '--use-pytorch-cross-attention' },
        ],
        description: 'Attention configuration options. Available values: --use-split-cross-attention, --use-quad-cross-attention, --use-pytorch-cross-attention.',
    },
    {
        name: '--cpu-vae',
        type: 'checkbox',
        description: 'Run the VAE on the CPU.',
        prefix: false,
    },
    {
        name: '--force-channels-last',
        type: 'checkbox',
        description: 'Force channels last format when inferencing the models.',
        prefix: false,
    },
    {
        name: '--directml',
        type: 'number',
        defaultValue: -1,
        description: 'Use torch-directml.',
        prefix: true,
    },
    {
        name: '--disable-ipex-optimize',
        type: 'checkbox',
        description: 'Disables ipex.optimize when loading models with Intel GPUs.',
        prefix: false,
    },
    {
        name: '--disable-xformers',
        type: 'checkbox',
        description: 'Disable xformers.',
        prefix: false,
    },
    {
        name: 'upcast',
        type: 'select',
        options: [
            { value: '--force-upcast-attention', label: '--force-upcast-attention' },
            { value: '--dont-upcast-attention', label: '--dont-upcast-attention' },
        ],
        description: 'Upcast configuration options. Available values: --force-upcast-attention, --dont-upcast-attention.',
    },
    {
        name: 'vram',
        type: 'select',
        options: [
            { value: '--gpu-only', label: '--gpu-only' },
            { value: '--highvram', label: '--highvram' },
            { value: '--normalvram', label: '--normalvram' },
            { value: '--lowvram', label: '--lowvram' },
            { value: '--novram', label: '--novram' },
            { value: '--cpu', label: '--cpu' },
        ],
        description: 'VRAM usage configuration options. Available values: --gpu-only, --highvram, --normalvram, --lowvram, --novram, --cpu.',
    },
    {
        name: '--reserve-vram',
        type: 'number',
        defaultValue: 0,
        description: 'Set the amount of VRAM in GB you want to reserve for use by your OS/other software. By default, some amount is reserved depending on your OS.',
        prefix: true,
    },
    {
        name: '--default-hashing-function',
        type: 'text',
        defaultValue: 'sha256',
        description: 'Allows you to choose the hash function to use for duplicate filename / contents comparison. Default is sha256.',
        prefix: true,
    },
    {
        name: '--disable-smart-memory',
        type: 'checkbox',
        description: 'Force ComfyUI to aggressively offload to regular RAM instead of keeping models in VRAM when it can.',
        prefix: false,
    },
    {
        name: '--deterministic',
        type: 'checkbox',
        description: 'Make PyTorch use slower deterministic algorithms when it can. Note that this might not make images deterministic in all cases.',
        prefix: false,
    },
    {
        name: '--fast',
        type: 'checkbox',
        description: 'Enable some untested and potentially quality deteriorating optimizations.',
        prefix: false,
    },
    {
        name: '--dont-print-server',
        type: 'checkbox',
        description: "Don't print server output.",
        prefix: false,
    },
    {
        name: '--quick-test-for-ci',
        type: 'checkbox',
        description: 'Quick test for CI.',
        prefix: false,
    },
    {
        name: '--windows-standalone-build',
        type: 'checkbox',
        description: 'Windows standalone build: Enable convenient things that most people using the standalone windows build will probably enjoy (like auto opening the page on startup).',
        prefix: false,
    },
    {
        name: '--disable-metadata',
        type: 'checkbox',
        description: 'Disable saving prompt metadata in files.',
        prefix: false,
    },
    {
        name: '--disable-all-custom-nodes',
        type: 'checkbox',
        description: 'Disable loading all custom nodes.',
        prefix: false,
    },
    {
        name: '--multi-user',
        type: 'checkbox',
        description: 'Enables per-user storage.',
        prefix: false,
    },
    {
        name: '--verbose',
        type: 'checkbox',
        description: 'Enables more debug prints.',
        prefix: false,
    },
    {
        name: '--front-end-version',
        type: 'text',
        defaultValue: 'comfyanonymous/ComfyUI@latest',
        description: 'Specifies the version of the frontend to be used. This command needs internet connectivity to query and download available frontend implementations from GitHub releases.',
        prefix: true,
    },
    {
        name: '--front-end-root',
        type: 'text',
        defaultValue: '',
        description: 'The local filesystem path to the directory where the frontend is located. Overrides --front-end-version.',
        prefix: true,
    },
];

export default argumentsConfig;
